name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  one_of: ^1.5.0
  dart_oneof_utils: ^0.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
