name: dart_oneof_utils
description: dart-oneof utils
version: 0.0.1
homepage: https://github.com/fa0311/dart-oneof-utils

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  one_of: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
